### PR TITLE
Update version number inside plugin.php

### PR DESCRIPTION
**Pull request by drorsnir**
This will make puns (the update plugin) stop complaining

### CODE REVIEW

**Comment by tomslominski** [comment]
Thanks for contibuting! Presumably PUNS looks at the latest release on GitHub, so would it not need to be plugin.php version 1.1.1 included in a 1.1.1 release to stop it complaining?

**Comment by drorsnir** [comment]
It reads from the plugin header as well, comparing that version to what it
can get from the repository. It calls yourls_get_plugins(), which in turn
calls yourls_get_plugin_data() that opens the file and "Capture all the
header within first comment block".

It doesn't check a hash or anything like that, so it doesn't know what
current version is installed other than through the header:

image

**Comment by tomslominski** [comment]
Thanks!

**Comment by drorsnir** [comment]
Thank you for your quick response :-)

**Pull request merged**
